### ISSUE TITLE
loop removed without understanding why

### ISSUE THREAD

**Issue by rpau** [rpau/walkmod-dead-code-cleaner-plugin#1]
https://github.com/rpau/java-symbol-solver

private static TypeUsage replaceNameParam(String name, TypeUsage newValue, TypeUsage typeToBeExamined) {
        if (typeToBeExamined.isTypeVariable()){
            if (typeToBeExamined.getTypeName().equals(name)) {
                return newValue;
            } else {
                return typeToBeExamined;
            }
        }
        int i = 0;
        for (TypeUsage param : typeToBeExamined.parameters()) {
            typeToBeExamined = typeToBeExamined.replaceParam(i, replaceNameParam(name, newValue, typeToBeExamined.parameters().get(i)));
            i++;
        }
        return typeToBeExamined;
    }

**Comment by rpau** [comment]
another case:

  @Override
    public TypeUsage getUsage(Node node) {
        for (TypeParameter tp : this.getTypeParameters()){
            throw new UnsupportedOperationException("Find parameters of "+this+" in "+node);
        }
        return new TypeUsageOfTypeDeclaration(this);
    }

**Comment by rpau** [comment]
@ftomassetti, when you have a gap, I recommend you to update your walkmod.xml to use the version of walkmod-dead-code-cleaner-plugin to: [1.0.0, 2.0.0) to receive the next bugs solved during the next executions.

**Comment by ftomassetti** [comment]
Done, thank you!
