### ISSUE TITLE
Transformation chain fails

### ISSUE THREAD

**Issue by iteratoruk** [rpau/walkmod-dead-code-cleaner-plugin#2]
I am attempting to use the walkmod-dead-code-cleaner-plugin via the maven-walkmod-plugin. I have a very simple test project with the following:

pom.xml (snippet from build/plugins -- aside from this plugin, the pom is an absolutely minimal spring-boot pom):

``` xml
<plugin>
    <groupId>org.walkmod</groupId>
    <artifactId>maven-walkmod-plugin</artifactId>
    <version>1.2</version>
    <executions>
        <execution>
            <phase>generate-sources</phase>
            <goals>
                <goal>check</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

 And walkmod.xml

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.0.dtd">
<walkmod>
    <plugins>
        <plugin groupId="org.walkmod" artifactId="walkmod-dead-code-cleaner-plugin" version="1.0.3" />
    </plugins>
    <transformation type="walkmod:commons:unused-declarations-cleaner" />
</walkmod>
```

And a simple test class with some unused declarations of various types:

``` java

package org.walkmod.test;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import java.util.ArrayList;

@SpringBootApplication
public class App {

    private boolean used;

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }

    private void unused() {}

}
```

Whenever I call `mvn install` I get an error during the walkmod:check saying "TRANSFORMATION CHAIN FAILS". Executing `mvn install -e` provides no additional stacktrace info.

It was noticeable that using just the walkmod-imports-cleaner-plugin did work and correctly identified the unused import statement in my test class.

**Comment by rpau** [comment]
Hi,

To use this plugin, you need to specify the way the classpath is resolved. If your project is using maven, you need to add the walkmod-maven-plugin.

All is explained in this GitHub project home page (the README file). So replace your walkmod configuration for the specified in the usage section of this page: https://github.com/rpau/walkmod-dead-code-cleaner-plugin

Let me know if it works. I guess that you want to say `walkmod apply` or `walkmod check`, but not `walkmod install`.  If the flag '-e' is enabled, something about the classpath should appear.

**Comment by iteratoruk** [comment]
Thanks -- I tried with the walkmod-maven-plugin as per readme but had a Guice creation error `No scope is bound to org.apache.maven.SessionScoped` (using Maven 3.2.3) so actually I guess the problem may lie there.

The walkmod.xml with maven conf-provider looks like:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE walkmod PUBLIC "-//WALKMOD//DTD" "http://www.walkmod.com/dtd/walkmod-1.0.dtd">
<walkmod>
    <plugins>
        <plugin groupId="org.walkmod" artifactId="walkmod-maven-plugin" version="2.0.1" />
        <plugin groupId="org.walkmod" artifactId="walkmod-dead-code-cleaner-plugin" version="1.0.3" />
    </plugins>
    <conf-providers>
        <conf-provider type="walkmod:commons:maven" />
    </conf-providers>
    <transformation type="walkmod:commons:unused-declarations-cleaner" />
</walkmod>
```

(With everything else being the same)

**Comment by rpau** [comment]
Can you try to run the example from the command line tool instead of the maven-walkmod-plugin?
Is the same error appearing? Could you send me the stacktrace?

Thank you for your feedback!

**Comment by iteratoruk** [comment]
[out.txt](https://github.com/rpau/walkmod-dead-code-cleaner-plugin/files/35588/out.txt) shows the command line tool output for the same project, which experiences the same error. Looks as though it may be attempting to execute `mvn` one directory up (i.e. not in the project root)?? (Project root is /users/christopher/work/space/walkmod-test)

Liking the tool very much, btw! :)

**Comment by rpau** [comment]
Hi,

Sorry if I asking too much, but could you also send me the pom.xml to reproduce exactly your project classpath?

Is a maven multimodule project? If so, are you running walkmod from the parent module or the submodule?

Thank you very much for your time. Once I fixed it, I will notify you.

**Comment by iteratoruk** [comment]
Sure -- no problem. See 
[pom.xml.txt](https://github.com/rpau/walkmod-dead-code-cleaner-plugin/files/35610/pom.xml.txt)

The test case I made to sanity check is dead simple; no multimodule ... although I guess it is possible that the spring-boot-maven-plugin could be messing with something. I'll try without and see what happens.

**Comment by iteratoruk** [comment]
FYI: removing spring-boot stuff doesn't resolve

**Comment by rpau** [comment]
I think that it is a bug on the walkmod-maven-plugin. I have applied some changes the last week. Let me today to fix it and I will send you a message here :)

**Comment by rpau** [comment]
Hi corinthino,

You have a parent project, what is happening is that walkmod understands this as a multimodule project.

``` xml
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.2.5.RELEASE</version>
</parent>
```

So, I have not taken this case into consideration. Let me fix it.

**Comment by rpau** [comment]
Solved! Upgrade your walkmod-maven-plugin version to 2.0.2
In some minutes should be available :)
Let me know if it has worked!

**Comment by iteratoruk** [comment]
Yep, that's done the trick - thanks! :)

**Comment by rpau** [comment]
Thanks to you to report a problem ;)

**Comment by kkorada** [comment]
hi @rpau what is difference between **walkmod-maven-plugin** and **maven-walkmod-plugin**,
i have currently **maven-walkmod-plugin** in my pom.xml, what should i use ?
